service: <%= name %>
provider:
  name: aws
  region: <%= region %>
  runtime: nodejs6.10
  stage: develop
  environment: '${file(.env.yml):${self:custom.stage}}'
custom:
  stage: "${opt:stage, self:provider.stage}"
package:
  include:
    - node_modules/**
  exclude:
    - .env.yml
    - .env.yml.example
    - templates/**
functions:
  authorizer-jwt:
    handler: functions/authorizer-jwt/handler.handler
  get-example:
    name: get-example
    description: Get example method description
    handler: functions/example/get.handler
    events:
      - http:
          method: GET
          path: example
          cors: true
          authorizer: authorizer-jwt
  post-example:
    name: post-example
    description: Post example method description
    handler: functions/example/post.handler
    events:
      - http: POST example
  put-example:
    name: put-example
    description: Put example method description
    handler: functions/example/put.handler
    events:
      - http: PUT example
  delete-example:
    name: delete-example
    description: Delete example method description
    handler: functions/example/delete.handler
    events:
      - http: DELETE example
resources:
  Resources:
    ApiGatewayRestApi:
      Type: 'AWS::ApiGateway::RestApi'
      Properties:
        Name: 'Serverless RESTful API (${self:custom.stage})'
